### ISSUE TITLE
insta-crashes the game

### ISSUE THREAD

**Issue by Jssekekekrr** [SMOLKEYS/MusiChaos#1]
the mod crashes Mindustry instantly upon loading. this is pretty easy to cause as is, just have the Spore Biomechs and Minable Resources mods installed, they don't even need to be both activated, just one being activated crashes the game instantly. these happen primarily with big mods, like Betamindy(apparently, even though it's not that big) and Exogenesis(especially Exogenesis, if the device can't handle it).

I'm pretty sure that your mod overloads the game(like with the previously mentioned pair of mods that crash the game by both being there), Mindustry can be easy to crash when it comes to adding additional things(that aren't built into the mod that is, like importing content from outside the mod's code)

**Comment by SMOLKEYS** [comment]
Send in a crash log.

(Although, I may already have a slight idea on what causes it...)

**Comment by Jssekekekrr** [comment]
It's failing to send
